// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API 错误响应
 */
export type ApiError = { 
/**
 * 错误类型
 */
error_type: string, 
/**
 * 错误消息
 */
message: string, 
/**
 * HTTP 状态码
 */
status_code: number, };