// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigError } from "./ConfigError";
import type { EngineError } from "./EngineError";
import type { HardwareError } from "./HardwareError";
import type { TrainingError } from "./TrainingError";
import type { WorkerError } from "./WorkerError";

/**
 * OpenMini 应用程序统一错误类型
 *
 * 这是所有公开 API 的错误返回类型，封装了各子系统的具体错误。
 * 通过 `From<T>` 实现自动从子错误类型转换。
 *
 * # 错误变体说明
 *
 * - `Engine` - 推理引擎相关错误（KV Cache、注意力计算等）
 * - `Worker` - 任务调度/工作线程相关错误
 * - `Training` - 模型训练相关错误
 * - `Hardware` - GPU/CPU/SIMD 硬件操作错误
 * - `Config` - 配置文件解析和验证错误
 * - `Io` - 文件 I/O 和网络 I/O 错误
 * - `Internal` - 内部逻辑错误（用于未知或临时性错误）
 *
 * # 示例
 *
 * ```rust,ignore
 * fn handle_inference() -> Result<Vec<f32>, AppError> {
 *     // 自动转换 EngineError -> AppError::Engine
 *     validate_kv_cache()?;
 *
 *     // 自动转换 HardwareError -> AppError::Hardware
 *     allocate_gpu_memory()?;
 *
 *     Ok(compute_output())
 * }
 * ```
 */
export type AppError = { "Engine": EngineError } | { "Worker": WorkerError } | { "Training": TrainingError } | { "Hardware": HardwareError } | { "Config": ConfigError } | { "Internal": string };