// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatChoice } from "./ChatChoice";
import type { UsageInfo } from "./UsageInfo";

/**
 * 聊天完成响应
 */
export type ChatCompletionResponse = { 
/**
 * 唯一请求ID
 */
id: string, 
/**
 * 对象类型
 */
object: string, 
/**
 * 创建时间戳
 */
created: bigint, 
/**
 * 模型名称
 */
model: string, 
/**
 * 选择列表
 */
choices: Array<ChatChoice>, 
/**
 * 使用统计
 */
usage: UsageInfo | null, };