// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

/**
 * 聊天选择项
 */
export type ChatChoice = { 
/**
 * 索引
 */
index: number, 
/**
 * 消息内容
 */
message: ChatMessage, 
/**
 * 完成原因
 */
finish_reason: string, };