// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaChoice } from "./DeltaChoice";

/**
 * 流式聊天 chunk
 */
export type ChatCompletionChunk = { 
/**
 * 唯一请求ID
 */
id: string, 
/**
 * 对象类型
 */
object: string, 
/**
 * 创建时间戳
 */
created: bigint, 
/**
 * 模型名称
 */
model: string, 
/**
 * 选择列表
 */
choices: Array<DeltaChoice>, };