// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 聊天消息
 */
export type ChatMessage = { 
/**
 * 角色: system/user/assistant
 */
role: string, 
/**
 * 消息内容
 */
content: string, };