// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

/**
 * 聊天完成请求
 */
export type ChatCompletionRequest = { 
/**
 * 会话ID（可选，用于上下文管理）
 */
session_id: string | null, 
/**
 * 消息列表
 */
messages: Array<ChatMessage>, 
/**
 * 是否流式输出
 */
stream: boolean, };