// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个组件健康状态
 */
export type ComponentHealth = { 
/**
 * 组件名称: gpu, memory, scheduler, model
 */
name: string, 
/**
 * 是否健康
 */
healthy: boolean, 
/**
 * 详细信息（可选）
 */
message: string | null, };