// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 配置管理错误类型 (错误码前缀: CFG)
 *
 * 涵盖应用配置的解析、验证和缺失等问题。
 *
 * # 配置文件位置
 *
 * 1. **默认路径**: `./config/server.toml`
 * 2. **环境变量覆盖**: `OPENMINI_CONFIG_PATH=/path/to/config.toml`
 * 3. **命令行参数**: `openmini-server --config /path/to/config.toml`
 *
 * # 配置验证规则
 *
 * - 必填字段缺失会立即报错（如 `model.path`）
 * - 数值范围会在启动时验证（如 `server.port > 0 && port < 65536`）
 * - 类型错误会在 TOML 解析阶段捕获
 */
export type ConfigError = { "ParsingFailed": string } | { "InvalidValue": string } | { "MissingConfig": string };