// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-Core Actor 设置
 */
export type CoreSettings = { 
/**
 * 使用的 CPU 核心数
 */
count: number, };