// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaContent } from "./DeltaContent";

/**
 * 流式增量选择
 */
export type DeltaChoice = { 
/**
 * 索引
 */
index: number, 
/**
 * 增量内容
 */
delta: DeltaContent, 
/**
 * 完成原因
 */
finish_reason: string | null, };