// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 增量内容
 */
export type DeltaContent = { 
/**
 * 角色流（仅第一个chunk）
 */
role: string | null, 
/**
 * 内容增量
 */
content: string | null, };