// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 推理引擎错误类型 (错误码前缀: ENG)
 *
 * 涵盖模型推理过程中的核心计算错误，主要涉及：
 * - KV Cache 维度和行数验证
 * - 数组内存布局检查
 * - 流式注意力机制写入操作
 *
 * # 常见场景
 *
 * 1. **模型加载阶段** - KV Cache 维度不匹配通常表示模型权重与配置不一致
 * 2. **推理执行阶段** - 流式写入失败可能由内存不足或并发冲突引起
 * 3. **批量推理** - 行数不匹配常发生在连续批处理（Continuous Batching）中
 */
export type EngineError = { "KvCacheDimensionMismatch": { 
/**
 * 期望的维度大小
 */
expected: number, 
/**
 * 实际获得的维度大小
 */
actual: number, } } | { "KvCacheRowMismatch": { 
/**
 * 期望的行数
 */
expected: number, 
/**
 * 实际获得的行数
 */
actual: number, } } | "ArrayNotContiguous" | { "StreamingAttentionWriteFailed": string };