// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * gRPC 通信设置
 */
export type GrpcSettings = { 
/**
 * 最大消息大小(MB)
 */
max_message_size_mb: number, 
/**
 * Keepalive 时间(毫秒)
 */
keepalive_time_ms: bigint, 
/**
 * Keepalive 超时时间(毫秒)
 */
keepalive_timeout_ms: bigint, };