// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 硬件层错误类型 (错误码前缀: HW)
 *
 * 涵盖与底层硬件交互的所有错误，包括 GPU、CPU SIMD、缓存管理等。
 *
 * # 平台支持
 *
 * | 平台 | 支持的后端 | 备注 |
 * |------|-----------|------|
 * | NVIDIA GPU | CUDA | 需要 CUDA Toolkit >= 11.8 |
 * | Apple Silicon | Metal | macOS 13+ |
 * | AMD GPU | Vulkan | 实验性支持 |
 * | x86_64 CPU | AVX2/SSE4.2 | 自动特性检测 |
 * | ARM64 CPU | NEON | aarch64 默认支持 |
 *
 * # 性能调优提示
 *
 * - **GPU 内存**: 启用 KV Cache 分页可显著降低显存需求
 * - **SIMD 加速**: 确保 CPU 支持 AVX2 可获得 4x Softmax 加速
 * - **多 GPU**: 当前版本单卡优化，多卡支持开发中
 */
export type HardwareError = { "MemoryAllocationFailed": string } | { "GpuOperationFailed": string } | { "SimdNotSupported": string } | { "CacheOperationFailed": string };