// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 健康检查器配置
 */
export type HealthCheckerConfig = { 
/**
 * GPU利用率警告阈值 (0-100)
 */
gpu_warning_threshold: number, 
/**
 * GPU利用率错误阈值 (0-100)
 */
gpu_error_threshold: number, 
/**
 * 内存使用率警告阈值 (0-100)
 */
memory_warning_threshold: number, 
/**
 * 内存使用率错误阈值 (0-100)
 */
memory_error_threshold: number, 
/**
 * CPU使用率警告阈值 (0-100)
 */
cpu_warning_threshold: number, 
/**
 * 队列长度警告阈值
 */
queue_length_warning: number, };