// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 健康检查响应
 */
export type HealthCheckResponse = { 
/**
 * 服务状态
 */
status: string, 
/**
 * 版本号
 */
version: string, 
/**
 * 启动时间
 */
uptime_seconds: bigint, };