// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentHealth } from "./ComponentHealth";

/**
 * 健康检查状态
 *
 * 包含整体状态、各组件详细信息和时间戳。
 */
export type HealthStatus = { 
/**
 * 整体状态: healthy/degraded/unhealthy
 */
status: string, 
/**
 * 各组件状态
 */
components: Array<ComponentHealth>, 
/**
 * 响应时间戳 (ISO 8601 格式字符串)
 *
 * **注意**: 在 Rust 中使用 DateTime<Utc>，
 * 但在 TypeScript 中导出为 string 类型以保持兼容性。
 */
timestamp: string, };