// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图像理解请求
 */
export type ImageUnderstandRequest = { 
/**
 * 会话ID
 */
session_id: string | null, 
/**
 * Base64 编码的图像数据
 */
image: string, 
/**
 * 问题文本
 */
question: string | null, };