// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图像理解响应
 */
export type ImageUnderstandResponse = { 
/**
 * 唯一请求ID
 */
id: string, 
/**
 * 图像描述/回答
 */
description: string, };