// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 内存管理设置
 */
export type MemorySettings = { 
/**
 * 最大可用内存(GB)
 */
max_memory_gb: number, 
/**
 * 模型占用内存上限(GB)
 */
model_memory_gb: number, 
/**
 * KV 缓存内存上限(GB)
 */
cache_memory_gb: number, 
/**
 * Arena 分配器大小(MB)
 */
arena_size_mb: number, };