// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型信息
 */
export type ModelInfo = { 
/**
 * 模型ID
 */
id: string, 
/**
 * 模型名称
 */
name: string, 
/**
 * 是否支持多模态
 */
multimodal: boolean, 
/**
 * 上下文长度
 */
context_length: number, };