// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型加载设置
 */
export type ModelSettings = { 
/**
 * 模型文件路径
 */
path: string, 
/**
 * 量化类型 (如 Q4_K_M, Q8_0 等)
 */
quantization: string, 
/**
 * 上下文长度
 */
context_length: number, 
/**
 * 架构类型: native | deepseek_v3 | gemma3
 */
architecture: string, };