// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一任务调度器配置 (TaskScheduler)
 *
 * 替代原有的 [thread_pool] 和 [worker] 配置，
 * 提供基于 Tokio Runtime 的单进程高效任务调度。
 */
export type SchedulerSettings = { 
/**
 * 最大并发任务数 (默认 = CPU 核心数)
 */
max_concurrent: number, 
/**
 * 任务队列容量 (超出将返回错误)
 */
queue_capacity: number, 
/**
 * 任务类型: "blocking" | "async" | "auto"
 */
worker_type: string, 
/**
 * 批处理大小
 */
batch_size: number, 
/**
 * 批处理超时 (ms)
 */
batch_timeout_ms: bigint, };