// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSettings } from "./CoreSettings";
import type { DatabaseSettings } from "./DatabaseSettings";
import type { EngineSettings } from "./EngineSettings";
import type { GrpcSettings } from "./GrpcSettings";
import type { MemorySettings } from "./MemorySettings";
import type { MoESettings } from "./MoESettings";
import type { ModelSettings } from "./ModelSettings";
import type { ServerSettings } from "./ServerSettings";
import type { ThreadPoolSettings } from "./ThreadPoolSettings";
import type { VisionSettings } from "./VisionSettings";
import type { WorkerSettings } from "./WorkerSettings";

/**
 * 服务器完整配置
 *
 * 包含所有子系统配置的顶层结构
 */
export type ServerConfig = { 
/**
 * 服务器基础设置
 */
server: ServerSettings, 
/**
 * 线程池设置
 */
thread_pool: ThreadPoolSettings, 
/**
 * 内存管理设置
 */
memory: MemorySettings, 
/**
 * 模型加载设置
 */
model: ModelSettings, 
/**
 * MoE 配置
 */
moe: MoESettings, 
/**
 * 视觉编码器配置
 */
vision: VisionSettings, 
/**
 * 引擎配置
 */
engine: EngineSettings, 
/**
 * Worker 进程设置
 */
worker: WorkerSettings, 
/**
 * Per-Core Actor 设置
 */
core: CoreSettings, 
/**
 * gRPC 通信设置
 */
grpc: GrpcSettings, 
/**
 * 数据库设置
 */
database: DatabaseSettings, };