// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务器基础设置
 */
export type ServerSettings = { 
/**
 * 监听主机地址
 */
host: string, 
/**
 * 监听端口号
 */
port: number, 
/**
 * 最大连接数
 */
max_connections: number, 
/**
 * 请求超时时间(毫秒)
 */
request_timeout_ms: bigint, };