// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * STT 响应
 */
export type SttResponse = { 
/**
 * 识别的文本
 */
text: string, 
/**
 * 置信度 (0.0-1.0)
 */
confidence: number, };