// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * STT 请求
 */
export type SttRequest = { 
/**
 * 音频数据（Base64编码）
 */
audio_data: string, };