// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 线程池设置
 */
export type ThreadPoolSettings = { 
/**
 * 线程池大小
 */
size: number, 
/**
 * 每个线程的栈大小(KB)
 */
stack_size_kb: number, };