// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型训练错误类型 (错误码前缀: TRN)
 *
 * 涵盖模型训练全流程中的错误，包括数据加载、前向/反向传播、优化器更新等。
 *
 * # 架构说明
 *
 * 训练模块支持：
 * - GRPO (Group Relative Policy Optimization) 强化学习训练
 * - AMP (Automatic Mixed Precision) 混合精度训练
 * - 分布式检查点保存/加载
 * - 自定义数据加载器
 *
 * # 常见错误模式
 *
 * 1. **形状不匹配** - 张量操作时维度不一致（最常见）
 * 2. **数值溢出** - 梯度爆炸或 NaN 出现
 * 3. **内存不足** - 大 batch 或长序列导致 OOM
 */
export type TrainingError = { "TensorOperationFailed": string } | { "GradientComputationFailed": string } | { "OptimizerStepFailed": string } | { "CheckpointFailed": string } | { "DataLoadingFailed": string };