// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TTS 请求
 */
export type TtsRequest = { 
/**
 * 要转换的文本
 */
text: string, 
/**
 * 音调 (-20.0 到 20.0)
 */
pitch: number, };