// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 使用统计信息
 */
export type UsageInfo = { 
/**
 * 提示 token 数
 */
prompt_tokens: number, 
/**
 * 完成 token 数
 */
completion_tokens: number, 
/**
 * 总 token 数
 */
total_tokens: number, };