// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作线程/任务调度错误类型 (错误码前缀: WRK)
 *
 * 涵盖任务调度系统中的并发和通信问题，主要涉及：
 * - 互斥锁操作（锁中毒检测）
 * - 任务队列通信（channel 发送/接收）
 * - 线程创建和管理（spawn 失败）
 *
 * # 常见场景
 *
 * 1. **高并发场景** - 锁中毒通常由 panic 导致的锁未释放引起
 * 2. **资源耗尽** - spawn 失败可能因达到操作系统线程数限制
 * 3. **关闭期间** - 通信错误常发生在调度器关闭后的任务提交
 */
export type WorkerError = "LockPoisoned" | { "CommunicationError": string } | { "SpawnFailed": string };