// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Worker 进程设置
 */
export type WorkerSettings = { 
/**
 * Worker 进程数量
 */
count: number, 
/**
 * 失败时是否自动重启
 */
restart_on_failure: boolean, 
/**
 * 健康检查间隔(毫秒)
 */
health_check_interval_ms: bigint, };